<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Admin access' => '',
    'Are you sure you want to delete this item?' => '',
    'Could not connect to database. Please check your credentials.' => '',
    'Create Picture' => '',
    'Created At' => '',
    'Database' => '',
    'Delete' => '',
    'Dislikes' => '',
    'Error saving configuration file. Please check file permissions.' => '',
    'Filename' => '',
    'General' => '',
    'Hidden' => '',
    'Home' => '',
    'ID' => '',
    'Language' => '',
    'Likes' => '',
    'Login' => '',
    'Logout' => '',
    'Ok, seems like there is no pictures yet. Be the first to upload one' => '',
    'Password must be at least 8 characters long and contain at least one number.' => '',
    'Passwords do not match.' => '',
    'Pictures' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Shared' => '',
    'The requested page does not exist.' => '',
    'Those are the basic config params, but you can find more in your .env file' => '',
    'Update' => '',
    'Update Picture: {name}' => '',
    'Uploaded From' => '',
    'Views' => '',
    'Wedding picture sharer is an application lovely created by {brand}' => '',
    'Wedding picture sharer is an aplication lovely created by {brand}' => '@@@@',
];
