<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Acerca de',
    'Admin access' => 'Acceso de administrador',
    'Are you sure you want to delete this item?' => '¿Estás seguro de que quieres eliminar este elemento?',
    'Create Picture' => 'Crear Imagen',
    'Created At' => 'Creado el',
    'Database' => 'Base de datos',
    'Delete' => 'Eliminar',
    'Dislikes' => 'No me gusta',
    'Filename' => 'Nombre de archivo',
    'General' => 'General',
    'Hidden' => 'Oculto',
    'Home' => 'Inicio',
    'ID' => 'ID',
    'Language' => 'Idioma',
    'Likes' => 'Me gusta',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar sesión',
    'Password must be at least 8 characters long and contain at least one number.' => 'La contraseña debe tener al menos 8 caracteres y contener al menos un número.',
    'Passwords do not match.' => 'Las contraseñas no coinciden.',
    'Pictures' => 'Imágenes',
    'Reset' => 'Restablecer',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Shared' => 'Compartido',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Update' => 'Actualizar',
    'Update Picture: {name}' => 'Actualizar Imagen: {name}',
    'Uploaded From' => 'Cargado desde',
    'Views' => 'Vistas',
    'Wedding picture sharer is an application lovely created by {brand}' => 'Wedding picture sharer es una aplicación creada con amor desde {brand}',
    'Could not connect to database. Please check your credentials.' =>  'No se pudo conectar a la base de datos. Por favor, verifica tus credenciales.',
    'Error saving configuration file. Please check file permissions.' => 'Error al guardar el archivo de configuración. Por favor, verifica los permisos del archivo.',
    'Ok, seems like there is no pictures yet. Be the first to upload one' => 'Ok, parece que aún no hay imágenes. ¡Sé el primero en subir una!',
    'Those are the basic config params, but you can find more in your .env file' => 'Estos son los parámetros de configuración básicos, pero puedes encontrar más en tu archivo .env',
    'Could not connect to the database. Please check your credentials.' => '@@No se pudo conectar a la base de datos. Por favor, verifica tus credenciales.@@',
    'Error saving the configuration file. Please check file permissions.' => '@@Error al guardar el archivo de configuración. Por favor, verifica los permisos del archivo.@@',
    'Those are the basic config params, but you can find more in your .env file.' => '@@Estos son los parámetros de configuración básicos, pero puedes encontrar más en tu archivo .env.@@',
];
